import {escapeHtml as e} from './ui.js';
import {icon} from './icons.js';
import {openDialog,confirmDialog} from './dialog.js';

let ctx,settings,devices,renderId=0;
const buttonIcon=(name,label,action)=>`<button class="icon-button" data-setting="${action}" aria-label="${label}" title="${label}">${icon(name)}</button>`;
const input=(key,label,value='',type='text',extra='')=>`<label>${label}<input name="${key}" type="${type}" value="${type==='password'?'':e(value??'')}" ${type==='password'?'autocomplete="new-password"':''} ${extra}></label>`;
const enabled=row=>`<label class="check-label"><input type="checkbox" name="enabled" ${row.enabled!==false?'checked':''}>启用此接入</label>`;
const credentials=row=>`<p class="help">${row.credential_set?'凭据已保存，留空会保留原值。':'每个接入使用独立凭据。'}</p>`;
function row(action,glyph,title,subtitle,count=''){return `<button class="setting-row" data-setting="${action}"><span class="setting-icon">${icon(glyph)}</span><span class="setting-label"><strong>${title}</strong><small>${e(subtitle)}</small></span>${count!==''?`<span class="setting-count">${e(count)}</span>`:''}${icon('chevron')}</button>`;}
export async function renderSettings(context){
  ctx=context;const id=++renderId,target=document.querySelector('#settings-content');
  if(!target.childElementCount)target.innerHTML='<div class="settings-loading" role="status">正在读取设置…</div>';
  const [s,d]=await Promise.all([ctx.request('/api/settings'),ctx.request('/api/mobile/devices')]);if(id!==renderId)return;settings=s;devices=d;
  target.innerHTML=`<div class="settings-grid">
    <section class="settings-card account-card"><span class="account-avatar">${e(ctx.session.username.slice(0,1).toUpperCase())}</span><div class="account-info"><h2>${e(ctx.session.username)}</h2><p>${e(location.host)}</p></div><div class="account-actions">${buttonIcon('sync','立即同步所有服务','sync')}${buttonIcon('password','修改密码','password')}${buttonIcon('logout','退出账号','logout')}</div></section>
    <section class="settings-card appearance-card"><div><h2>外观</h2><p class="help">让工作台适应你的光线。</p></div><div class="appearance-switch" role="group" aria-label="外观">${[['dark','moon','深色'],['system','monitor','跟随系统'],['light','sun','浅色']].map(([choice,glyph,label])=>`<button type="button" data-appearance="${choice}" aria-label="${label}" title="${label}" aria-pressed="${ctx.getAppearance()===choice}">${icon(glyph)}</button>`).join('')}</div></section>
    <section class="settings-card settings-services"><header><h2>外部服务</h2><p class="help">独立管理，集中查看。</p></header>${row('github','github','GitHub 任务','工作流与微信步数',Object.keys(s.github_tasks||{}).length+(s.github?1:0))}${row('mail','mail','Gmail 邮箱','多个邮箱，统一收件箱',Object.keys(s.gmail_accounts||{}).length)}${row('servers','server','服务器','1Panel v2 与 Beszel',Object.keys(s.server_sources||{}).length)}${row('network','network','网络检测','连通性与地区节点',s.network.nodes.length)}</section>
    <section class="settings-card settings-preferences"><header><h2>偏好与数据</h2><p class="help">简单设置，安心使用。</p></header>${row('general','clock','时间与历史',s.timezone+' · 保留 '+s.history_days+' 天')}${row('devices','phone','手机通知',d.devices.length?'管理已登记的 App 设备':'安装 App，接收手机提醒',d.devices.length)}${row('backup','backup','配置备份','加密导出与恢复配置')}</section>
  </div>`;
  target.querySelectorAll('[data-appearance]').forEach(button=>button.onclick=()=>ctx.setAppearance(button.dataset.appearance));
  target.querySelectorAll('[data-setting]').forEach(button=>button.onclick=()=>handle(button.dataset.setting,button));
}
async function refresh(){await renderSettings(ctx);}
export function openSettingsTarget(section,id='') {
  if(section==='network')network();
  else if(section==='devices')deviceManager();
  else if(id && (section==='github' && id==='wxstep' ? settings.github : settings[collections[section]]?.[id]))editor(section,id);
  else if(collections[section])manager(section);
}
async function save(body,dialog){await ctx.request('/api/settings',{method:'PUT',body});dialog.close();await refresh();ctx.toast('设置已保存，服务将在后台同步。');}
function bindForm(dialog,callback){const form=dialog.querySelector('form');form.onsubmit=async event=>{event.preventDefault();const button=form.querySelector('[type=submit]');button.disabled=true;dialog.feedback('');try{await callback(Object.fromEntries(new FormData(form)));}catch(error){dialog.feedback(error.message,true);}finally{if(button.isConnected)button.disabled=false;}};return form;}
async function handle(action,button){
  try{
    if(action==='sync'){button.disabled=true;button.classList.add('syncing');ctx.toast('正在同步 GitHub、邮箱、服务器与网络…');try{await ctx.request('/api/command',{method:'POST',body:{action:'sync/all',payload:{}}});ctx.toast('同步完成，请查看工作台。');}finally{button.disabled=false;button.classList.remove('syncing');}}
    else if(action==='logout'){if(await confirmDialog('退出账号','配置保存在后端，重新登录后仍会保留。','退出账号'))await ctx.logout();}
    else if(action==='password')password();
    else if(action==='general')general();
    else if(action==='network')network();
    else if(action==='devices')deviceManager();
    else if(action==='backup')backup();
    else manager(action);
  }catch(error){ctx.toast(error.message,true);}
}
function password(){const dialog=openDialog('修改密码',`<form>${input('current_password','当前密码','','password','required')}${input('new_password','新密码','','password','required minlength="12" maxlength="256"')}<p class="help">至少 12 个字符。修改后需要重新登录。</p><div class="dialog-actions"><button class="primary" type="submit">修改密码</button></div></form>`);bindForm(dialog,async data=>{await ctx.request('/api/password',{method:'POST',body:data});dialog.close();await ctx.logout().catch(()=>{});location.reload();});}
function general(){const zones=[...new Set(['Asia/Shanghai','Asia/Hong_Kong','Asia/Tokyo','Asia/Singapore','UTC','Europe/London','Europe/Berlin','America/New_York','America/Los_Angeles',...(Intl.supportedValuesOf?.('timeZone')||[]),settings.timezone])];const dialog=openDialog('时间与历史',`<form><label>时区<select name="timezone">${zones.map(zone=>`<option value="${e(zone)}" ${zone===settings.timezone?'selected':''}>${e(zone)}</option>`).join('')}</select></label>${input('history_days','历史保留天数',settings.history_days,'number','required min="1" max="365"')}<div class="dialog-actions"><button class="primary" type="submit">保存</button></div></form>`);bindForm(dialog,data=>save({timezone:data.timezone,history_days:Number(data.history_days)},dialog));}
function network(){const dialog=openDialog('网络检测',`<form>${enabled(settings.network)}<p class="help">检测位置是运行 MyDesk 后端的服务器。</p><label>地区节点<textarea name="nodes" rows="7" placeholder="名称=域名或 IP">${e(settings.network.nodes.map(n=>n.name+'='+n.host).join('\n'))}</textarea></label><p class="help">每行一个节点，例如：示例节点=example.com</p><div class="dialog-actions"><button class="primary" type="submit">保存</button></div></form>`);bindForm(dialog,data=>{const nodes=data.nodes.split('\n').filter(l=>l.trim()).map(line=>{const separator=line.indexOf('=');if(separator<1||!line.slice(separator+1).trim())throw new Error('每行需要填写名称=域名或 IP');return {name:line.slice(0,separator).trim(),host:line.slice(separator+1).trim()};});return save({network:{enabled:data.enabled==='on',nodes}},dialog);});}
function deviceManager(){const dialog=openDialog('手机通知',`<p class="help">网页创建的定时提醒会同步到已登录的 App，由手机本地执行。设备登记不代表当前在线。</p><div class="manager-list">${devices.devices.map(d=>`<article class="managed-row"><span class="setting-icon">${icon('phone')}</span><div class="setting-label"><strong>${e(d.name)}</strong><small>本地提醒 ${d.local_alarm?'已登记':'未启用'} · 推送 ${d.push_registered?'已登记':'未配置'}</small></div><button class="text-button danger" data-device="${e(d.id)}">移除</button></article>`).join('')||'<div class="empty">还没有登记的设备，请在 App 中登录。</div>'}</div>`);dialog.querySelectorAll('[data-device]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{await ctx.request('/api/mobile/devices/'+encodeURIComponent(button.dataset.device),{method:'DELETE'});dialog.close();await refresh();deviceManager();}catch(error){dialog.feedback(error.message,true);button.disabled=false;}});}
const collections={github:'github_tasks',mail:'gmail_accounts',servers:'server_sources'};
const managerTitles={github:'GitHub 任务',mail:'Gmail 邮箱',servers:'服务器'};
function manager(kind){
  const collection=collections[kind],entries=Object.entries(settings[collection]||{});
  if(kind==='github'&&settings.github)entries.unshift(['wxstep',{...settings.github,name:'微信步数'}]);
  const dialog=openDialog(managerTitles[kind],`<div class="filter-bar"><input type="search" placeholder="搜索名称或地址" aria-label="搜索接入"><button class="primary add-source" type="button">${icon('plus')} 添加</button></div><div class="manager-list"></div><p class="help">${kind==='github'?'每项独立保存 Token，不与其他任务共用。':'已有凭据不会展示，编辑时留空保留。'}</p>`);
  const draw=()=>{const q=dialog.querySelector('input').value.toLowerCase();dialog.querySelector('.manager-list').innerHTML=entries.filter(([,item])=>`${item.name} ${item.username||item.repo||item.url||''}`.toLowerCase().includes(q)).map(([id,item])=>`<button class="setting-row" data-edit="${e(id)}"><span class="setting-icon">${icon(kind==='github'?'github':kind==='mail'?'mail':'server')}</span><span class="setting-label"><strong>${e(item.name)}</strong><small>${e(kind==='github'?`${item.owner}/${item.repo}`:kind==='mail'?item.username:item.url)}</small></span><span class="source-state">${item.enabled===false?'已停用':'已配置'}</span>${icon('chevron')}</button>`).join('')||'<div class="empty">还没有匹配的接入。</div>';dialog.querySelectorAll('[data-edit]').forEach(button=>button.onclick=()=>editor(kind,button.dataset.edit));};dialog.querySelector('input').oninput=draw;dialog.querySelector('.add-source').onclick=()=>editor(kind);draw();
}
function editor(kind,id=null){
  const collection=collections[kind],isSteps=id==='wxstep';const existing=id?(isSteps?settings.github:settings[collection]?.[id]):null;
  const item=existing||{enabled:true,provider:'1panel',limit:5,ref:'main',adapter:'workflow',step:'MyDesk result',max_age_hours:36};
  const name=kind==='github'?'任务':kind==='mail'?'邮箱':'服务器';
  const field=(key,label,type='text',extra='')=>input(key,label,item[key],type,extra);
  const githubFields=`${isSteps?'':`<label>任务用途<select name="purpose"><option value="task">自动任务</option><option value="steps" ${isSteps?'selected':''}>微信步数</option></select></label>`}<div class="form-row">${field('owner','仓库所有者','text','required')}${field('repo','仓库名称','text','required')}</div><div class="form-row">${field('workflow','工作流文件名','text','required placeholder="checkin.yml"')}${field('ref','分支','text','required')}</div>${field('token','GitHub Token','password')}${isSteps?'':`<label>结果读取<select name="adapter">${[['workflow','工作流执行状态'],['standard','MyDesk 标准结果'],['52fzwg','52 辅助论坛'],['glados','GLaDOS']].map(([v,t])=>`<option value="${v}" ${item.adapter===v?'selected':''}>${t}</option>`).join('')}</select></label><div class="adapter-step">${field('step','结果步骤名称')}</div>${field('max_age_hours','超过多久未执行需要提醒（小时）','number','required min="1" max="8760" step="0.5"')}`}`;
  const mailFields=`${field('username','Gmail 地址','email','required')}${field('password','应用专用密码','password')}<label>展示邮件数量<select name="limit">${[3,4,5].map(n=>`<option value="${n}" ${n===item.limit?'selected':''}>${n} 封</option>`).join('')}</select></label><details class="advanced"><summary>后端代理（可选）</summary><div class="form-row">${input('proxy_host','代理主机',item.proxy?.host||'','text','placeholder="127.0.0.1"')}${input('proxy_port','代理端口',item.proxy?.port||'','number','min="1" max="65535"')}</div><p class="help">填写后端可以访问的 HTTP CONNECT 代理地址。</p></details>`;
  const serverFields=`<label>监控类型<select name="provider"><option value="1panel" ${item.provider==='1panel'?'selected':''}>1Panel v2</option><option value="beszel" ${item.provider==='beszel'?'selected':''}>Beszel</option></select></label>${field('url','面板根地址','url','required placeholder="https://panel.example.com"')}<div data-provider="1panel">${field('api_key','API Key','password')}<label>签名方式<select name="signature"><option value="md5" ${item.signature!=='hmac-sha256'?'selected':''}>兼容模式</option><option value="hmac-sha256" ${item.signature==='hmac-sha256'?'selected':''}>HMAC-SHA256</option></select></label></div><div data-provider="beszel">${field('email','登录邮箱','email')}${field('password','密码','password')}</div>`;
  const dialog=openDialog(`${existing?'编辑':'添加'}${name}`,`<form>${isSteps?'<p class="help">微信步数 · GitHub 工作流</p>':field('name',name+'名称','text','required maxlength="100"')}${isSteps?'':enabled(item)}${kind==='github'?githubFields:kind==='mail'?mailFields:serverFields}${credentials(item)}<div class="dialog-actions"><button class="primary" type="submit">保存${name}</button>${existing?'<button class="secondary" data-check type="button">检查连接</button>':''}</div>${existing?'<button class="text-button danger remove-source" type="button">移除此接入</button>':''}</form>`,{wide:true});
  const form=bindForm(dialog,async data=>{
    const latest=await ctx.request('/api/settings');let payload;
    if(kind==='github'&&(isSteps||data.purpose==='steps')){if(!isSteps&&latest.github)throw new Error('微信步数已有接入，请先编辑或移除现有配置。');if(id&&!isSteps)throw new Error('已有自动任务不能直接改为微信步数，请新增接入。');payload={github:{owner:data.owner.trim(),repo:data.repo.trim(),workflow:data.workflow.trim(),ref:data.ref.trim(),...(data.token?{token:data.token.trim()}:{})}};}
    else{
      const row={name:data.name.trim(),enabled:data.enabled==='on'};
      if(kind==='github'){for(const key of ['owner','repo','workflow','ref','adapter','step'])row[key]=data[key]?.trim()||'';row.max_age_hours=Number(data.max_age_hours);if(data.token)row.token=data.token.trim();}
      else if(kind==='mail'){row.username=data.username.trim();row.limit=Number(data.limit);if(data.password)row.password=data.password.replaceAll(' ','');for(const key of ['host','mailbox'])if(item[key])row[key]=item[key];row.proxy=data.proxy_host.trim()?{host:data.proxy_host.trim(),port:Number(data.proxy_port)}:null;}
      else{row.provider=data.provider;row.url=data.url.trim().replace(/\/$/,'');if(data.provider==='1panel'){row.signature=data.signature;if(data.api_key)row.api_key=data.api_key;}else{row.email=data.email.trim();if(data.password)row.password=data.password;if(item.public_url)row.public_url=item.public_url;}}
      payload={[collection]:{...latest[collection],[id||'source_'+crypto.randomUUID().replaceAll('-','').slice(0,12)]:row}};
    }
    await save(payload,dialog);
  });
  if(kind==='servers'){const update=()=>form.querySelectorAll('[data-provider]').forEach(panel=>panel.hidden=panel.dataset.provider!==form.elements.provider.value);form.elements.provider.onchange=update;update();}
  if(kind==='github'&&!isSteps){const update=()=>{const steps=form.elements.purpose.value==='steps';form.elements.adapter.closest('label').hidden=steps;form.elements.max_age_hours.closest('label').hidden=steps;form.elements.max_age_hours.required=!steps;form.querySelector('.adapter-step').hidden=steps||form.elements.adapter.value==='workflow';};form.elements.adapter.onchange=update;form.elements.purpose.onchange=update;update();}
  dialog.querySelector('[data-check]')?.addEventListener('click',async event=>{const button=event.currentTarget;button.disabled=true;try{const result=await ctx.request('/api/command',{method:'POST',body:{action:kind==='github'?'github_task/check':'service/check',payload:kind==='github'?{task_id:id}:{kind:kind==='mail'?'mail':'servers',id}}});dialog.feedback(result.message||result.result?.message||'连接检查完成',result.connected===false);}catch(error){dialog.feedback(error.message,true);}finally{button.disabled=false;}});
  dialog.querySelector('.remove-source')?.addEventListener('click',async()=>{dialog.close();if(await confirmDialog('移除此接入','只移除这项接入，不影响其他服务。','移除')){try{const latest=await ctx.request('/api/settings');const body=isSteps?{github:null}:{[collection]:Object.fromEntries(Object.entries(latest[collection]||{}).filter(([key])=>key!==id))};await ctx.request('/api/settings',{method:'PUT',body});await refresh();ctx.toast('接入已移除。');}catch(error){ctx.toast(error.message,true);}}else editor(kind,id);});
}
function backup(){
  const dialog=openDialog('配置备份',`<p class="help">备份包含服务配置与凭据，使用密码加密。账号、提醒和历史记录不会导出。</p><form class="export-form">${input('password','备份密码','','password','required minlength="12" maxlength="256"')}<button class="primary" type="submit">导出加密备份</button></form><div class="backup-divider"></div><form class="import-form"><label>选择备份文件<input name="file" type="file" accept=".mydesk,application/json" required></label>${input('password','备份密码','','password','required minlength="12" maxlength="256"')}<label>恢复方式<select name="mode"><option value="merge">合并已有配置</option><option value="replace">替换全部配置</option></select></label><button class="secondary" type="submit">预览恢复内容</button></form>`);
  const exportForm=dialog.querySelector('.export-form');exportForm.onsubmit=async event=>{event.preventDefault();const button=exportForm.querySelector('button');button.disabled=true;try{const result=await ctx.request('/api/backup/export',{method:'POST',body:{password:new FormData(exportForm).get('password'),appearance:ctx.getAppearance()}});const url=URL.createObjectURL(new Blob([JSON.stringify(result.file)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=result.filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);exportForm.reset();dialog.feedback('加密备份已导出，请妥善保存文件与密码。');}catch(error){dialog.feedback(error.message,true);}finally{button.disabled=false;}};
  const importForm=dialog.querySelector('.import-form');importForm.onsubmit=async event=>{event.preventDefault();const button=importForm.querySelector('button');button.disabled=true;try{const data=new FormData(importForm),file=data.get('file');if(file.size>128*1024)throw new Error('备份文件过大');const preview=await ctx.request('/api/backup/preview',{method:'POST',body:{file:JSON.parse(await file.text()),password:data.get('password'),mode:data.get('mode'),current_appearance:ctx.getAppearance()}});dialog.close();showBackupPreview(preview);}catch(error){dialog.feedback(error.message,true);}finally{button.disabled=false;}};
}
function showBackupPreview(preview){const names={github_tasks:'GitHub 任务',gmail_accounts:'Gmail 邮箱',server_sources:'服务器'};const dialog=openDialog('确认恢复配置',`<p class="help">${preview.mode==='replace'?'将替换现有配置。':'将与现有配置合并。'}请确认下面的变更。</p><div class="backup-summary"><div class="detail-row"><span>时区与历史</span><strong>${e(preview.timezone)} · ${e(preview.history_days)} 天</strong></div><div class="detail-row"><span>外观</span><strong>${({system:'跟随系统',dark:'深色',light:'浅色'})[preview.appearance]||'跟随系统'}</strong></div><div class="detail-row"><span>微信步数 / 网络节点</span><strong>${preview.steps_configured?'已配置':'未配置'} / ${e(preview.network_nodes)} 个</strong></div>${Object.entries(preview.counts||{}).map(([key,c])=>`<div class="detail-row"><span>${names[key]||e(key)}</span><strong>新增 ${c.added} · 更新 ${c.updated} · 移除 ${c.removed}</strong></div>`).join('')}</div>${(preview.changes||[]).map(change=>`<p class="help">${e(change.name)} · ${{added:'新增',updated:'更新',removed:'移除'}[change.action]||e(change.action)}</p>`).join('')}<div class="dialog-actions"><button class="secondary" data-cancel>取消</button><button class="primary" data-apply>确认恢复</button></div>`);dialog.querySelector('[data-cancel]').onclick=()=>dialog.close();dialog.querySelector('[data-apply]').onclick=async event=>{const button=event.currentTarget;button.disabled=true;try{const result=await ctx.request('/api/backup/apply',{method:'POST',body:{preview_id:preview.preview_id,confirmed:true}});if(result.appearance)ctx.setAppearance(result.appearance);dialog.close();await refresh();ctx.toast(result.message||'配置已恢复。');}catch(error){dialog.feedback(error.message,true);button.disabled=false;}};}
